user:
  username: long_test
server:
  port: 8992

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/config_dev
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update

    show-sql: false
    open-in-view: true
